file:
  upload-dir: C:/Users/lucas/Documents/workspace/intelliJ/file-upload-download-demo/filesDestinationDir

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB